# @package exadra37-docker/ubuntu-oh-my-zsh
# @link    https://gitlab.com/u/exadra37-docker/ubuntu-oh-my-zsh
# @link    https://hub.docker.com/r/exadra37/ubuntu-oh-my-zsh
# @since   2016/10/30
# @license MIT
# @author  Exadra37(Paulo Silva) <exadra37ingmailpointcom>
#
# Social Links:
# @link    Author:   https://exadra37.com
# @link    Gitlab:   https://gitlab.com/Exadra37
# @link    Github:   https://github.com/Exadra37
# @link    Docker:   https://hub.docker.com/u/exadra37/
# @link    Linkedin: https://uk.linkedin.com/in/exadra37
# @link    Twitter:  https://twitter.com/Exadra37

FROM ubuntu:latest
MAINTAINER Exadra37(Paulo Silva) <exadra37ingmailpointcom>


RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
